FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Foodpanda Public Mobile API



# Mobile API v5 Root [/]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

It is recommend to follow the “url” link values,
[Link](https://tools.ietf.org/html/rfc5988) or Location headers where
applicable to retrieve resources. Instead of constructing your own URLs,
to keep your client decoupled from implementation details.

# Group SMS Verification

## Confirm customer [/api/v5/customers/confirm?language_id=]

+ Parameters
    + language_id (optional, number, `1`) ... ID of the language used for SMS-template. If empty, the user's default language is used.

### Send confirmation code via SMS [POST]

+ Request
    + Headers

            Authorization: AccessToken

+ Response 200 (application/json)
    + Body

            {
                "data": null
            }