FORMAT: 1A
HOST: http://api-st.foodpanda.in/

# Foodpanda Public Mobile API

# Group SMS Verification

## Confirm customer [/api/v5/customers/confirm?language_id=]

+ Parameters
    + language_id (optional, number, `1`) ... ID of the language used for SMS-template. If empty, the user's default language is used.

### Send confirmation code via SMS [POST]

+ Request
    + Headers

            Authorization: RefreshToken

+ Response 200 (application/json)
    + Body

            {
                "status_code": 200,
                "data": null
            }