FORMAT: 1A
HOST: http://api-st.foodpanda.in/

# Foodpanda Public Mobile API

<!--
## API Blueprint
+ [Previous: Grouping Resources](04.%20Grouping%20Resources.md)
+ [This: Raw API Blueprint](https://path/to/this)
+ [Next: Requests](06.%20Requests.md)
-->

# Group SMS Verification

This API describes endpoints related to Customer verification via SMS.

## Customer confirmation [/api/v5/customers/confirmation{?language_id}]

+ Parameters

    + language_id: 1 (number, optional) - ID of the language used for SMS-template. If empty, the user's default language is used.

### Retrieve confirmation status [GET]

Checks whether the currently logged in customer is already verified or not

+ Request

    + Headers
    
            Authorization: AccessToken
            X-FP-API-KEY: ?
    
+ Response 200 (application/json)

        {
            "is_verified": true,
            "mobile_phone": "722123456"
        }
    
+ Response 200 (text/plain)

        "is_verified": true

### Send verification-code via SMS [POST]

Sends a new verification code to the user's mobile phone.

+ Request

    + Headers
    
            Authorization: AccessToken
            X-FP-API-KEY: ?

+ Response 200 (application/json)

    + Body

            {
                "status_code": 200,
                "data": null
            }

## Update mobile phone number for customer [/api/v5/customers/mobilephone/]

Updates the mobile phone number for the currently logged in user

### Update mobile phone number [PUT]

+ Request (application/json)

    + Headers
    
            Authorization: AccessToken
            X-FP-API-KEY: ?

    + Body

            {
                "mobile_phone": "250 123456789"
            }
    
+ Response 200 (application/json)

    + Attributes (User Model)

# Group Order

Endpoints related to a customer's order

## Order information [/api/v5/orders/{order_code}/info{?cart_calculation}]

+ Parameters

    + order_code: `v6wr-l7nk` (string, required) - Order code to fetch info for
    + cart_calculation: true (boolean, optional) - Whether to add reorder information to response

### Retrieve order information [GET]

Fetches all informations about the order for the provided order code

+ Request

    + Headers
    
            Authorization: AccessToken
            X-FP-API-KEY: iphone
            
+ Response 200 (application/json)

        {
            "status_code": 200,
            "data": {
                "status_history": [{
                    "code": 2,
                    "message": "Awaiting confirmation from vendor",
                    "type": "temporary",
                    "changed_at": {
                        "date": "2015-07-17 12:33:07",
                        "timezone_type": 3,
                        "timezone": "Asia\/Kolkata"
                    }
                }],
                "order_review": {
                    "is_reviewable": true,
                    "review": {
                        "id": 150163,
                        "vendor_id": "10835",
                        "customer_id": "2540716",
                        "customer_name": "Saurav",
                        "comment": null,
                        "rating": "2",
                        "date": "2015-06-16",
                        "rating_type": null,
                        "review_external_url": null,
                        "external_review_openrice_score": null,
                        "title": null
                    }
                } 
                "order_address": "Flat No. \/ House No.:  jmeter\njmeter\n10 th cross\nBangalore",
                "order_id": 4103524,
                "order_code": "v6wr-l7nk",
                "ordered_at": {
                    "date": "2015-07-17 12:33:05",
                    "timezone_type": 3,
                    "timezone": "Asia\/Kolkata"
                },
                "confirmed_delivery_time": {
                    "date": "2015-07-17 13:33:05",
                    "timezone_type": 3,
                    "timezone": "Asia\/Kolkata"
                },
                "order_cart": {
                    "order_is_reapeatable": true,
                    "order_is_repeatable_message": "<!-- formerly error_message -->",
                    "subtotal": 4740,
                    "subtotal_before_discount": 4740,
                    "subtotal_after_product_discount": 4740,
                    "subtotal_after_discount": 4740,
                    "subtotal_after_discount_and_delivery_fee": 4740,
                    "subtotal_after_discount_and_service_fee": 4740,
                    "subtotal_after_discount_and_delivery_fee_and_service_fee": 4740,
                    "total_value": 5731.23,
                    "group_joiner_total": 5731.23,
                    "container_charge": 0,
                    "delivery_fee": 0,
                    "vat_total": 725.79,
                    "voucher_total": 0,
                    "discount_total": 0,
                    "delivery_fee_discount": 0,
                    "service_tax_total": 265.44,
                    "service_fee_total": 0,
                    "vendorCart": [{
                        "vendor_id": 10835,
                        "is_open": true,
                        "subtotal": 4740,
                        "subtotal_before_discount": 4740,
                        "subtotal_after_product_discount": 4740,
                        "subtotal_after_discount": 4740,
                        "subtotal_after_discount_and_delivery_fee": 4740,
                        "subtotal_after_discount_and_service_fee": 4740,
                        "subtotal_after_discount_and_delivery_fee_and_service_fee": 4740,
                        "total_value": 5731.23,
                        "group_joiner_total": 5731.23,
                        "container_charge": 0,
                        "delivery_fee": 0,
                        "vat_total": 725.79,
                        "voucher_total": 0,
                        "discount_total": 0,
                        "delivery_fee_discount": 0,
                        "service_tax_total": 265.44,
                        "service_fee_total": 0,
                        "products": [{
                            "product_variation_id": 3980666,
                            "name": "*Margherita Pizza",
                            "variation_name": "",
                            "total_price_before_discount": 4740,
                            "total_price": 4740,
                            "quantity": 12,
                            "toppings": [],
                            "choices": [{
                                "id": 327473,
                                "name": "Papa's Original Crust",
                                "description": null,
                                "is_available": true
                            }],
                            "group_order_user_name": null,
                            "group_order_user_code": null,
                            "is_available": true
                        }],
                        "minimum_order_amount": 250,
                        "minimum_order_amount_difference": 0,
                        "discount_text": null
                    }],
                    "voucher": []
                },
                "internal_status_code": null,
                "sms_verification_needed": false
            }
        }

# Data Structures

## User Model (object)

+ first_name (string) - User's first name
+ last_name (string) - User's last name
+ email (string) - User's email address